# Using `python_requirements()` here results in:
# ">1 target exports this module, so it is ambiguous which to use"
# So, we explicitly list deps instead.
# python_requirements()

python_requirement(
    name="beautifulsoup4",
    requirements=["beautifulsoup4"],
)

python_requirement(
    name="flask",
    requirements=["flask"],
)

pack_metadata(
    name="metadata",
)
