python_sources(
    overrides={
        "app.py": {
            "dependencies": [
                "./controllers",
                "./controllers/v1",
                "./controllers/exp",
            ],
        },
    },
)
