files(
    name="apache_sample_conf",
    sources=["apache.sample.conf"],
)

files(
    name="htpasswd",
    sources=["htpasswd_dev"],
)

files(
    name="logging_console",
    sources=["console.conf"],
)

files(
    name="logging",
    sources=["logging.conf"],
)

files(
    name="logging_gunicorn",
    sources=["logging.gunicorn.conf"],
)

files(
    name="logging_syslog",
    sources=["syslog.conf"],
)
