# invoke must also be listed in pants.toml under [GLOBAL].plugins
python_requirement(
    name="invoke",
    requirements=["invoke"],
)

python_sources(
    # interpreter_constraints=[">=3.7,<3.10"]
    # skip_pylint=True,
)
