python_tests(
    name="tests",
    skip_pylint=True,
    tags=["integration"],
    stevedore_namespaces=[
		"orquesta.expressions.functions",
		"st2common.runners.runner",
	],
)

python_library(skip_pylint=True)
