python_library(
	name = "noop_runner_root",
	skip_pylint=True,
)

stevedore_extension(
    namespace = "st2common.runners.runner",
    entry_points = {
        "noop": "noop_runner.noop_runner",
    }
)
