stevedore_extension(
    name="runner",
    namespace="st2common.runners.runner",
    entry_points={
        "inquirer": "inquirer_runner.inquirer_runner",
    },
)

st2_runner_python_distribution(
    runner_name="inquirer",
    description=(
        "Inquirer action runner for StackStorm event-driven automation platform"
    ),
)
