# Using `python_requirements()` here results in:
# ">1 target exports this module, so it is ambiguous which to use"
# So, we explicitly list deps instead.
# python_requirements()

pack_metadata(
    name="metadata",
)
