python_sources()

# Please make sure to register all of the packs in this dir.
# For each pack, depend on the python_library target (which depends on pack_metadata).
target(
    name="all_packs",
    dependencies=[
        "./dummy_pack_4",
    ],
)
