# only one of these targets should be uncommented (pants_ or python_requirement)

#pants_requirements(
#    name="pants",
#    resolve="pants-plugins",
#    testutil=False,
#)

# this is a more restricted version of the above.
python_requirement(
    name="pants",
    resolve="pants-plugins",
    requirements=["pantsbuild.pants==2.11.0"],
)
