python_tests(
    name="tests",
    timeout=120,
    dependencies=[
        "st2client/tests/base.py",
        "st2client/tests/fixtures:st2client-ini",
    ],
    skip_pylint=True,
    tags=["unit"],
)

python_library(skip_pylint=True)
