files(
    name="pack-fixtures",
    sources=[
        "./generic/**/*.yaml",
        "./generic/**/*.sh",
        "./timers/**/*.yaml",
        "./rule_enforcements/**/*.yaml",
        "./descendants/**/*.yaml",
        "./aliases/**/*.yaml",
        "./traces/**/*.yaml",
        "./backstop/**/*.yaml",
        "./packs/orquesta_tests/**/*.yaml",
    ],
)

python_library()
