# python_sources(skip_pylint=True)  # setup.py

st2_component_python_distribution(
    component_name="st2reactor",
    dependencies=[
        "./st2reactor",
        "./st2reactor/cmd",
        "./st2reactor/container",
        "./st2reactor/sensor",
    ],
)
