python_library(skip_pylint=True)

# Ignore dist_utils with pants.
# These files are only needed for tests/unit/test_dist_utils.py
#   - requirements-used-for-tests.txt
#   - version_file.py

shell_library(
    name="fixtures0",
)
