python_tests(
    name="tests",
    skip_pylint=True,
    tags=["integration"],
    dependencies=[
        "conf/st2.tests.conf:st2_tests_conf",
        "conf/st2.tests2.conf:st2_tests_conf",
    ],
)

python_sources(skip_pylint=True)
