python_tests(
    name="tests",
    dependencies=["st2common/tests/unit/base.py"],
	uses=["mongo"],
    skip_pylint=True,
	tags=["unit"],
    stevedore_namespaces=["st2common.runners.runner"],
)

python_library(skip_pylint=True)
