pack_metadata(
    name="metadata",
)

python_library(
    dependencies=[
        ":metadata",
        "st2tests/st2tests/fixtures/packs/configs/dummy_pack_schema_with_nested_object_2.yaml",
    ],
)
