# used in st2common.constants.logging.DEFAULT_LOGGING_CONF_PATH
resources(
    name="base_logging_conf",
    sources=["base.logging.conf"],
)

python_sources(
    dependencies=[":base_logging_conf"],
)
