files(
    name="logging_console",
    sources=["console.conf"],
)

files(
    name="logging",
    sources=["logging.conf"],
)

files(
    name="logging_gunicorn",
    sources=["logging.gunicorn.conf"],
)

files(
    name="logging_syslog",
    sources=["syslog.conf"],
)
