#!/usr/bin/env bash

set -euo pipefail

# You can change these constants.
PYTHON_BIN=python3.6
VIRTUALENV=/tmp/st2/.venv
PIP="${VIRTUALENV}/bin/pip"
REQUIREMENTS_FILE=requirements-pants.txt
CONSTRAINTS_FILE=constraints-pants.txt

"${PYTHON_BIN}" -m venv "${VIRTUALENV}"
"${PIP}" install wheel
"${PIP}" install pip --upgrade
# Install all our requirements.txt, and also any 3rdparty
# dependencies specified outside requirements.txt, e.g. via a
# handwritten python_requirement_library target.
"${PIP}" install \
  -r "${REQUIREMENTS_FILE}" \
  -r <(./pants dependencies --type=3rdparty ::)
echo "# Generated by scripts/generate_constraints.sh on $(date)" > "${CONSTRAINTS_FILE}"
"${PIP}" freeze --all >> "${CONSTRAINTS_FILE}"

