stevedore_extension(
    name="runner",
    namespace="st2common.runners.runner",
    entry_points={
        "http-request": "http_runner.http_runner",
    },
)

st2_runner_python_distribution(
    runner_name="http",
    description=(
        "HTTP(s) action runner for StackStorm event-driven automation platform"
    ),
)
