python_library(skip_pylint=True)

stevedore_extension(
    name="runner",
    namespace="st2common.runners.runner",
    entry_points={
        "announcement": "announcement_runner.announcement_runner",
    },
)
