python_library(skip_pylint=True)

stevedore_extension(
	name="runner",
    namespace = "st2common.runners.runner",
    entry_points = {
        "action-chain": "action_chain_runner.action_chain_runner",
    }
)
