python_sources(skip_pylint=True)

stevedore_extension(
    name="runner",
    namespace="st2common.runners.runner",
    entry_points={
        "python-script": "python_runner.python_runner",
    },
)
